# Generated by Django 3.0.7 on 2020-07-06 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chofere',
            fields=[
                ('nombre', models.CharField(default='Ninungo', max_length=30, primary_key=True, serialize=False, verbose_name='Nombre del chofer')),
                ('fecha_contrato', models.DateField(verbose_name='Fecha de contrato')),
                ('edad', models.IntegerField(verbose_name='Edad del conductor')),
            ],
        ),
        migrations.CreateModel(
            name='unidade',
            fields=[
                ('numero', models.CharField(default='Unidad', max_length=30, primary_key=True, serialize=False, verbose_name='Número de la unidad')),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de adquisición')),
                ('chofer', models.ManyToManyField(to='base_dato.chofere', verbose_name='Nombre del conductor designado')),
            ],
        ),
        migrations.CreateModel(
            name='viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_viaje', models.IntegerField(verbose_name='Duración aproximada del viaje (hrs)')),
                ('fecha', models.DateField()),
                ('precio_viaje', models.FloatField(verbose_name='Precio del boleto')),
                ('asientos', models.IntegerField(verbose_name='Asientos disponibles')),
                ('hora', models.CharField(max_length=30, verbose_name='Hora a la que sale el viaje')),
                ('paradero', models.CharField(default='Paradero', max_length=30, verbose_name='Punto de partida')),
                ('destino', models.CharField(default='Destino', max_length=30, verbose_name='Destino final')),
                ('numero_unidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_dato.unidade', verbose_name='Número de la unidad')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('nombre', models.CharField(default=1, max_length=30, primary_key=True, serialize=False, verbose_name='Nombre del usuario')),
                ('fecha', models.DateField(verbose_name='Fecha en que viaja')),
                ('boletos', models.IntegerField(verbose_name='Boletos que compró')),
                ('hora', models.CharField(max_length=30, verbose_name='Hora a la que viaja')),
                ('unidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_dato.unidade', verbose_name='Unidad en la que viaja')),
            ],
        ),
    ]
