# Generated by Django 3.0.7 on 2020-07-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_dato', '0002_auto_20200706_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='unidad',
        ),
        migrations.AddField(
            model_name='usuario',
            name='unidad',
            field=models.ManyToManyField(to='base_dato.unidade', verbose_name='Unidad en la que viaja'),
        ),
    ]
